obj-$(CONFIG_MACH_MSM8974_T1_ATT) += board-8974-t1-us.o board-8974-t1-att-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_T1_USC) += board-8974-t1-us.o board-8974-t1-usc-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_T1LTE_GLOBAL_COM) += board-8974-t1lte-global-com.o board-8974-t1lte-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_T1WIFI_GLOBAL_COM) += board-8974-t1wifi-global-com.o board-8974-t1wifi-global-com-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_T1WIFIN_GLOBAL_COM) += board-8974-t1wifin-global-com.o board-8974-t1wifin-global-com-gpiomux.o

obj-$(CONFIG_LGE_BLUETOOTH) += board-8974-t1-rfkill.o
